# Generated by Django 2.2 on 2020-11-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('product', models.CharField(choices=[('AUT', 'Автокредит'), ('CNS', 'Потребительский'), ('SCR', 'Залог'), ('MTG', 'Ипотека')], max_length=3)),
                ('phone', models.CharField(max_length=10)),
                ('resolution', models.CharField(blank=True, choices=[('APR', 'Одобрено'), ('REF', 'Отказ'), ('HLD', 'Временный отказ')], max_length=3)),
                ('comment', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
